---
metrics:
  - name: Companies velocity metrics
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    series:
      - =company_;;_;all,kubernetes,cluster_lifecycle,apps,project_infra,docs,contrib,ui,project,node,autoscaling_and_monitoring,networking,clients,storage,api_machinery,misc,helm,multi_cluster;activity,authors,issues,prs,commits,review_comments,issue_comments,commit_comments,comments,contributions,contributors
    values:
      - =;;;Google,Independent,Red Hat,IBM,Microsoft,Huawei,CoreOS,ZTE,Intel,Cisco,Mirantis,VMware,Rackspace,HPE,SAP,Net EASE 网易有态度,Fujitsu,HP,Docker,eBay,Canonical,Pivotal,Apple,Bitnami,EasyStack,Samsung,Caicloud,Zalando,Devops,Ghostcloud,Heptio,Mesosphere,Tigera,Tencent,Weaveworks,Apprenda,Amadeus,SalesForce,Kinvolk,Oracle,Amazon,Shopify,ThoughtWorks,SuperAwesome,Apache,CNCF,Dell,SoundCloud,AT&T,Zhejiang University,GoDaddy,GitHub,Rancher,Infoblox,Yahoo,EMC,Bloomberg,SUSE,NFLabs,Atlassian,Giant Swarm,Apcera,Datadog,Cockroach Labs,Facebook,Box,The New York Times,Qiniu,Uber,Endocode
