---
metrics:
  - name: PRs merged by repository group
    periods: d,w,m,q,y
    aggregate: 1,7
    skip: w7,m7,q7,y7
    series:
      - group_prs_merged
    values:
      - =;;;API machinery,Apps,Autoscaling and monitoring,Clients,Cluster lifecycle,Contrib,Docs,Kubernetes,Misc,Multi-cluster,Networking,Node,Project,Project infra,Storage,UI,Helm
