---
vars:
  - name: reviewers_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/reviewers.html'
  - name: sig_mentions_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/sig_mentions.html'
