---
vars:
  - name: projects_partial_html
    type: s
    command:
      - cat
      - '{{datadir}}partials/projects.html'
  - name: reviewers_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/reviewers.md'
  - name: sig_mentions_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/sig_mentions.md'
