---
vars:
  - name: os_hostname
    type: s
    command: [hostname]
  - name: full_name
    type: s
    value: Kubernetes
  - name: projects_partial_html
    type: s
    command:
      - cat
      - '{{datadir}}partials/projects.html'
    replaces:
      - [hostname, os_hostname]
  - name: reviewers_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/reviewers.md'
  - name: sig_mentions_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/kubernetes/sig_mentions.md'
  - name: dashboards_docs_html
    type: s
    command:
      - cat
      - '{{datadir}}docs/dashboards/dashboards.md'
    replaces:
      - [hostname, os_hostname]
      - [full_name, full_name]
